name: Github Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17 to publish to GitHub Packages
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Publish to GitHub Packages
        run: mvn deploy --settings settings.xml -P github
        env:
          GITHUB_TOKEN: ${{ github.token }}
          CORREIOS_API_TOKEN: ${{ secrets.CORREIOS_API_TOKEN }}
          CORREIOS_CARTAO_POSTAGEM: ${{ secrets.CORREIOS_CARTAO_POSTAGEM }}
          CORREIOS_USER_ID: ${{ secrets.CORREIOS_USER_ID }}